---
 - name: WebServer | Create WEB Security Group
   local_action:
     module: ec2_group
     name: "{{ item.sg_name }}"
     description: "{{ item.sg_description }}"
     region: "{{ vpc_region }}" # Change the AWS region here
     vpc_id: "{{ vpc.vpc_id }}" # vpc is the resgister name, you can also set it manually
     state: present
     rules: "{{ item.sg_rules }}"
   with_items: "{{ web_security_groups }}"
   register: web_sg

 - name: WebServer | Tag the WEB Security Group with a name
   local_action:
     module: ec2_tag
     resource: "{{ item.group_id}}"
     region: "{{ vpc_region }}"
     state: present
     tags:
       Name: "{{ vpc_name }}-{{ item.item.sg_name }}"
   with_items: "{{ web_sg.results }}"
 
# - name: WebServer | Search for Ubuntu AMI
#   ec2_ami_search:
#     region: "{{ vpc_region|default('us-east-1') }}"
#     distro: "{{ linux_distribution }}"
#     release: "{{ ubuntu_release }}"
#     store: "{{ ami_store }}"
#     virt: "{{ virutalization_type }}"
#     arch: "{{ cpu_architecture }}"
#   register: imgae_id
 
 - name: WebServer1 | Create the 1st WebServer Instance
   local_action:
     module: ec2
     region: "{{ vpc_region }}"
     group: "{{ web_security_groups[0].sg_name }}"
     keypair: "{{ key_name }}"
     instance_type: "{{ web_instance_type }}"
     image: "{{ imgae_id_ami }}"
     vpc_subnet_id: "{{ item }}"
     assign_public_ip: True
     wait: True
     wait_timeout: 600
     user_data: |
               #!/bin/sh
               hostname "{{ host_name1 }}"
               echo "127.0.0.1 localhost {{ host_name1 }}" >> /etc/hosts
               echo {{ host_name1 }} > /etc/hostname 
               sudo yum install httpd -y
     instance_tags:
       Name: "{{ vpc_name }}_WebInstance-01"
       Environment: "{{ ENV }}"
       Role: "{{ server_role }}"
       Application: "{{ application }}"
   with_items:
      - "{{ public_subnet_1 }}"
   register: web1


 - name: WebServer2 | Create the 2nd WebServer Instance
   local_action:
     module: ec2
     region: "{{ vpc_region }}"
     group: "{{ web_security_groups[0].sg_name }}"
     keypair: "{{ key_name }}"
     instance_type: "{{ web_instance_type }}"
     image: "{{ imgae_id_ami }}"
     vpc_subnet_id: "{{ item }}"
     assign_public_ip: True
     wait: True
     wait_timeout: 600
     user_data: |
               #!/bin/sh
               hostname "{{ host_name2 }}"
               echo "127.0.0.1 localhost {{ host_name2 }}" >> /etc/hosts
               echo {{ host_name2 }} > /etc/hostname
               sudo yum install httpd -y
     instance_tags:
       Name: "{{ vpc_name }}_WebInstance-02"
       Environment: "{{ ENV }}"
       Role: "{{ server_role }}"
       Application: "{{ application }}"
   with_items:
     - "{{ public_subnet_2 }}"
   register: web2

 - name: WebServer | Set the Instances facts
   set_fact:
     instance_id_1: "{{ web1.results[0].instances[0].id }}"
     instance_id_2: "{{ web2.results[0].instances[0].id }}"

